{{- if .Values.ingress.enabled -}}
{{- $gatewaySvcPort := .Values.gateway.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  labels:
    name: {{ include "atoman.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
   - host: {{ .Values.ingress.atomanHost }}
     http:   
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gateway-service
              port:
                number: {{$gatewaySvcPort}} 
{{- end }}