#
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-cars
data:
  ocelot.cars.api.json: |-
      {
          "Routes": [
            {
              "DownstreamPathTemplate": "/api/ActOfTransfer/{everything}",
              "DownstreamScheme": "http",
              "DownstreamHostAndPorts": [
                {
                  "Host": "{{ .Values.cars.name }}",
                  "Port": {{ .Values.cars.service.port }}
                }
              ],
              "UpstreamPathTemplate": "/api/ActOfTransfer/{everything}",
              "UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
            },
            {
              "DownstreamPathTemplate": "/api/CarInfo/{everything}",
              "DownstreamScheme": "http",
              "DownstreamHostAndPorts": [
                {
                  "Host": "{{ .Values.cars.name }}",
                  "Port": {{ .Values.cars.service.port }}
                }
              ],
              "UpstreamPathTemplate": "/api/CarInfo/{everything}",
              "UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
            }
           ]
        }