#База данных заказов
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_STORAGE_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.storageDbName  | b64enc | quote }}
  DB_AUTH_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.authDbName  | b64enc | quote }}
  DB_CARS_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.carsDbName  | b64enc | quote }}
  REDIS_URI: {{ printf "redis://%s:%s@%s:%s/db" .Values.redis.global.redis.user .Values.redis.global.redis.password (include "redis.fullname" .) .Values.redis.global.redis.port  | b64enc | quote }}
  DB_EXPRESS_URI: {{ printf "mssql://%s:%s@%s/%s"   .Values.mssql.userName .Values.mssql.password .Values.mssql.server .Values.mssql.expressDbName  | b64enc | quote }}
  DB_LOGS_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.logsDbName  | b64enc | quote }}
---